/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change My Password
         * @description Let the authenticated user change their own password.
         */
        put: operations["change_my_password_api_v1_auth_me_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hotels
         * @description List all hotels. Platform-level action, admin only (owner console).
         */
        get: operations["list_hotels_api_v1_hotels_get"];
        put?: never;
        /**
         * Create Hotel
         * @description Create a new hotel (tenant). Platform-level action, admin only.
         */
        post: operations["create_hotel_api_v1_hotels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Hotel
         * @description Create a hotel and optionally bulk-import its rooms and staff, atomically.
         *
         *     All-or-nothing: if any row fails validation, nothing is committed — not even
         *     the hotel. All row errors are collected and returned together (422) so the
         *     caller can fix the whole file at once. Provisioned users share one temporary
         *     password (returned once) and must change it on first login.
         */
        post: operations["provision_hotel_api_v1_hotels_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hotel */
        get: operations["get_hotel_api_v1_hotels__hotel_id__get"];
        /** Update Hotel */
        put: operations["update_hotel_api_v1_hotels__hotel_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_hotels__hotel_id__users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_hotels__hotel_id__users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_hotels__hotel_id__users__user_id__get"];
        /** Update User */
        put: operations["update_user_api_v1_hotels__hotel_id__users__user_id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_hotels__hotel_id__users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rooms */
        get: operations["list_rooms_api_v1_hotels__hotel_id__rooms_get"];
        put?: never;
        /** Create Room */
        post: operations["create_room_api_v1_hotels__hotel_id__rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_v1_hotels__hotel_id__rooms__room_id__get"];
        /** Update Room */
        put: operations["update_room_api_v1_hotels__hotel_id__rooms__room_id__put"];
        post?: never;
        /** Delete Room */
        delete: operations["delete_room_api_v1_hotels__hotel_id__rooms__room_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms/{room_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Room Status
         * @description Change only a room's status. Available to managers and admins; the
         *     full add/rename/delete lifecycle is reserved for platform admins.
         */
        patch: operations["update_room_status_api_v1_hotels__hotel_id__rooms__room_id__status_patch"];
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_hotels__hotel_id__tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_hotels__hotel_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_hotels__hotel_id__tasks__task_id__get"];
        /** Update Task */
        put: operations["update_task_api_v1_hotels__hotel_id__tasks__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Task Status
         * @description Update only a task's status. Allowed for managers/admins, or the
         *     housekeeper the task is assigned to.
         */
        patch: operations["update_task_status_api_v1_hotels__hotel_id__tasks__task_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotelCreate */
        HotelCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
        };
        /**
         * HotelProvisionRequest
         * @description Create a hotel and (optionally) bulk-import its rooms and staff in one
         *     atomic operation. Both lists are optional; either or both may be empty.
         */
        HotelProvisionRequest: {
            hotel: components["schemas"]["HotelCreate"];
            /** Rooms */
            rooms?: components["schemas"]["RoomCreate"][];
            /** Users */
            users?: components["schemas"]["UserProvision"][];
        };
        /** HotelProvisionResponse */
        HotelProvisionResponse: {
            hotel: components["schemas"]["HotelRead"];
            /** Rooms Created */
            rooms_created: number;
            /** Users */
            users: components["schemas"]["UserRead"][];
            /** Temporary Password */
            temporary_password: string;
        };
        /** HotelRead */
        HotelRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HotelUpdate */
        HotelUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** RoomCreate */
        RoomCreate: {
            /** Room Number */
            room_number: string;
            /** Floor */
            floor?: number | null;
            /** Room Type */
            room_type?: string | null;
            /** @default clean */
            status: components["schemas"]["RoomStatus"];
        };
        /** RoomRead */
        RoomRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            /** Room Number */
            room_number: string;
            /** Floor */
            floor: number | null;
            /** Room Type */
            room_type: string | null;
            status: components["schemas"]["RoomStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoomStatus
         * @enum {string}
         */
        RoomStatus: "clean" | "dirty" | "in_progress" | "out_of_service";
        /**
         * RoomStatusUpdate
         * @description Status-only update. Managers may change a room's status without the
         *     full-edit (add/rename/delete) rights reserved for platform admins.
         */
        RoomStatusUpdate: {
            status: components["schemas"]["RoomStatus"];
        };
        /** RoomUpdate */
        RoomUpdate: {
            /** Room Number */
            room_number?: string | null;
            /** Floor */
            floor?: number | null;
            /** Room Type */
            room_type?: string | null;
            status?: components["schemas"]["RoomStatus"] | null;
        };
        /** TaskCreate */
        TaskCreate: {
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** @default pending */
            status: components["schemas"]["TaskStatus"];
            /** @default normal */
            priority: components["schemas"]["TaskPriority"];
            /** Notes */
            notes?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "normal" | "urgent";
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /** Assigned To */
            assigned_to: string | null;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /** Notes */
            notes: string | null;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "pending" | "assigned" | "in_progress" | "completed";
        /** TaskStatusUpdate */
        TaskStatusUpdate: {
            status: components["schemas"]["TaskStatus"];
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Room Id */
            room_id?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            /** Notes */
            notes?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserProvision
         * @description A staff row in a provisioning batch. No password: every provisioned user
         *     gets the batch's shared temporary password and must change it on first login.
         */
        UserProvision: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Hotel Id */
            hotel_id: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /** Must Change Password */
            must_change_password: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "manager" | "housekeeper";
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            /** Name */
            name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    change_my_password_api_v1_auth_me_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotels_api_v1_hotels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"][];
                };
            };
        };
    };
    create_hotel_api_v1_hotels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_hotel_api_v1_hotels_provision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelProvisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hotel_api_v1_hotels__hotel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hotel_api_v1_hotels__hotel_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_hotels__hotel_id__users_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_hotels__hotel_id__users_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_hotels__hotel_id__users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_hotels__hotel_id__users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_hotels__hotel_id__users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_api_v1_hotels__hotel_id__rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_v1_hotels__hotel_id__rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_v1_hotels__hotel_id__rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_api_v1_hotels__hotel_id__rooms__room_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_room_api_v1_hotels__hotel_id__rooms__room_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_status_api_v1_hotels__hotel_id__rooms__room_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_hotels__hotel_id__tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                assigned_to?: string | null;
            };
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_hotels__hotel_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_hotels__hotel_id__tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_hotels__hotel_id__tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_status_api_v1_hotels__hotel_id__tasks__task_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
