/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Start a self-service password reset.
         *
         *     Always returns the same generic 200 whether or not the email matches a
         *     user, so the endpoint never reveals which addresses have accounts.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Consume a reset token and set a new password.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update My Preferences
         * @description Update the authenticated user's own UI preferences (theme, language).
         */
        patch: operations["update_my_preferences_api_v1_auth_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change My Password
         * @description Let the authenticated user change their own password.
         */
        put: operations["change_my_password_api_v1_auth_me_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hotels
         * @description List all hotels. Platform-level action, admin only (owner console).
         */
        get: operations["list_hotels_api_v1_hotels_get"];
        put?: never;
        /**
         * Create Hotel
         * @description Create a new hotel (tenant). Platform-level action, admin only.
         */
        post: operations["create_hotel_api_v1_hotels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Hotel
         * @description Create a hotel and optionally bulk-import its rooms and staff, atomically.
         *
         *     All-or-nothing: if any row fails validation, nothing is committed — not even
         *     the hotel. All row errors are collected and returned together (422) so the
         *     caller can fix the whole file at once. Provisioned users share one temporary
         *     password (returned once) and must change it on first login.
         */
        post: operations["provision_hotel_api_v1_hotels_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hotel
         * @description View a hotel's profile. Manager+ only — housekeepers have no feature that
         *     needs it. Managers are scoped to their own hotel; admins are cross-tenant.
         */
        get: operations["get_hotel_api_v1_hotels__hotel_id__get"];
        /** Update Hotel */
        put: operations["update_hotel_api_v1_hotels__hotel_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_hotels__hotel_id__users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_hotels__hotel_id__users__user_id__get"];
        /** Update User */
        put: operations["update_user_api_v1_hotels__hotel_id__users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rooms */
        get: operations["list_rooms_api_v1_hotels__hotel_id__rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_v1_hotels__hotel_id__rooms__room_id__get"];
        /** Update Room */
        put: operations["update_room_api_v1_hotels__hotel_id__rooms__room_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/rooms/{room_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Room Status
         * @description Change only a room's status. Available to managers and admins; the
         *     full add/rename/delete lifecycle is reserved for platform admins.
         */
        patch: operations["update_room_status_api_v1_hotels__hotel_id__rooms__room_id__status_patch"];
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_hotels__hotel_id__tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_hotels__hotel_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Dirty Rooms Endpoint
         * @description Bulk-import a list of dirty rooms (e.g. from a manager's CSV): set each
         *     room dirty, create a cleaning task per room, and optionally split the new
         *     tasks evenly across the chosen housekeepers. See the shared core in
         *     app/services/task_import.py for the full contract.
         */
        post: operations["import_dirty_rooms_endpoint_api_v1_hotels__hotel_id__tasks_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_hotels__hotel_id__tasks__task_id__get"];
        /** Update Task */
        put: operations["update_task_api_v1_hotels__hotel_id__tasks__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Task Status
         * @description Update only a task's status. Allowed for managers/admins, or the
         *     housekeeper the task is assigned to.
         */
        patch: operations["update_task_status_api_v1_hotels__hotel_id__tasks__task_id__status_patch"];
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hotel Access Requests
         * @description A manager sees their own hotel's requests (to track pending/decided).
         */
        get: operations["list_hotel_access_requests_api_v1_hotels__hotel_id__access_requests_get"];
        put?: never;
        /**
         * File Access Request
         * @description A manager asks a platform admin to add or remove a staff member or room.
         *     The request is only validated here; nothing is created/deleted until an
         *     admin approves it.
         */
        post: operations["file_access_request_api_v1_hotels__hotel_id__access_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Access Requests
         * @description The global queue across all hotels. Defaults to pending.
         */
        get: operations["list_access_requests_api_v1_access_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access-requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Access Request
         * @description Perform the requested add/remove and close the request in one
         *     transaction, so the record and the action can never diverge. Idempotent-
         *     guarded: acting on an already-decided request returns 409.
         */
        post: operations["approve_access_request_api_v1_access_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access-requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Access Request */
        post: operations["reject_access_request_api_v1_access_requests__request_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List a hotel's API keys (metadata only — secrets are never returned).
         */
        get: operations["list_api_keys_api_v1_hotels__hotel_id__api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Mint a new API key for a hotel. The full secret is returned exactly once;
         *     only its hash is stored, so it can never be shown again.
         */
        post: operations["create_api_key_api_v1_hotels__hotel_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Api Key
         * @description Revoke (disable) an API key. Idempotent — revoking an already-revoked key
         *     is a no-op. The row is kept so its prefix/last-used stay auditable.
         */
        delete: operations["revoke_api_key_api_v1_hotels__hotel_id__api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/pms/dirty-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pms Dirty Rooms
         * @description Machine-to-machine entry point for a PMS to push rooms that need cleaning.
         *
         *     Auth is a per-hotel API key (``X-API-Key`` header); the hotel is derived from
         *     the key, never from the request body. The payload is normalized by the default
         *     adapter, then handed to the shared import core (set rooms dirty, create tasks,
         *     optionally balance-assign to the named housekeepers). All-or-nothing: any
         *     unknown room or unmatched housekeeper fails the whole batch.
         */
        post: operations["pms_dirty_rooms_api_v1_integrations_pms_dirty_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessRequestCreate
         * @description A manager files this. `add` requires a resource-matched `payload` and no
         *     `target_id`; `remove` requires a `target_id` and no `payload`.
         */
        AccessRequestCreate: {
            resource: components["schemas"]["RequestResource"];
            kind: components["schemas"]["RequestKind"];
            /** Note */
            note?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Payload */
            payload?: components["schemas"]["StaffAddPayload"] | components["schemas"]["RoomAddPayload"] | null;
        };
        /**
         * AccessRequestDecision
         * @description Returned when an admin approves a request. For a staff `add`, the one-time
         *     temp password and the created user are surfaced so the admin can hand them
         *     over; other kinds return just the closed request.
         */
        AccessRequestDecision: {
            request: components["schemas"]["AccessRequestRead"];
            /** Temporary Password */
            temporary_password?: string | null;
        };
        /** AccessRequestRead */
        AccessRequestRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            resource: components["schemas"]["RequestResource"];
            kind: components["schemas"]["RequestKind"];
            status: components["schemas"]["RequestStatus"];
            /** Requested By */
            requested_by: string | null;
            /** Target Id */
            target_id: string | null;
            /** Payload */
            payload: Record<string, never> | null;
            /** Note */
            note: string | null;
            /** Decision Note */
            decision_note: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decided At */
            decided_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AccessRequestReject */
        AccessRequestReject: {
            /** Decision Note */
            decision_note?: string | null;
        };
        /**
         * ApiKeyCreate
         * @description Request to mint a new PMS API key for a hotel.
         */
        ApiKeyCreate: {
            /** Name */
            name: string;
        };
        /**
         * ApiKeyCreateResponse
         * @description Returned once at creation. `key` is the full secret and is never shown or
         *     stored again — the admin must copy it now.
         */
        ApiKeyCreateResponse: {
            api_key: components["schemas"]["ApiKeyRead"];
            /** Key */
            key: string;
        };
        /**
         * ApiKeyRead
         * @description A key's metadata. Never includes the secret — only the display prefix.
         */
        ApiKeyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DirtyRoomImportRequest
         * @description Manager/CSV path: rooms and housekeepers are already in canonical form
         *     (plain room-number strings and housekeeper user IDs).
         */
        DirtyRoomImportRequest: {
            /** Rooms */
            rooms?: string[];
            /** Housekeeper Ids */
            housekeeper_ids?: string[];
            /** @default normal */
            priority: components["schemas"]["TaskPriority"];
        };
        /** DirtyRoomImportResponse */
        DirtyRoomImportResponse: {
            /** Rooms Set Dirty */
            rooms_set_dirty: number;
            /** Tasks Created */
            tasks_created: number;
            /** Skipped */
            skipped: components["schemas"]["ImportSkip"][];
            /** Assignments */
            assignments: components["schemas"]["ImportAssignment"][];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotelCreate */
        HotelCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
        };
        /**
         * HotelProvisionRequest
         * @description Create a hotel and (optionally) bulk-import its rooms and staff in one
         *     atomic operation. Both lists are optional; either or both may be empty.
         */
        HotelProvisionRequest: {
            hotel: components["schemas"]["HotelCreate"];
            /** Rooms */
            rooms?: components["schemas"]["RoomCreate"][];
            /** Users */
            users?: components["schemas"]["UserProvision"][];
        };
        /** HotelProvisionResponse */
        HotelProvisionResponse: {
            hotel: components["schemas"]["HotelRead"];
            /** Rooms Created */
            rooms_created: number;
            /** Users */
            users: components["schemas"]["UserRead"][];
            /** Temporary Password */
            temporary_password: string;
        };
        /** HotelRead */
        HotelRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HotelUpdate */
        HotelUpdate: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
        };
        /** ImportAssignment */
        ImportAssignment: {
            /**
             * Housekeeper Id
             * Format: uuid
             */
            housekeeper_id: string;
            /** Name */
            name: string;
            /** Tasks Assigned */
            tasks_assigned: number;
        };
        /** ImportSkip */
        ImportSkip: {
            /** Room Number */
            room_number: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "existing_open_task" | "out_of_service";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PmsDirtyRoomsRequest
         * @description PMS path: deliberately permissive. `rooms` may be plain strings or objects
         *     carrying a room number under any accepted alias; `housekeepers` are names.
         *     The default adapter (app.services.pms_adapters) normalizes this.
         */
        PmsDirtyRoomsRequest: {
            /** Rooms */
            rooms?: unknown[];
            /** Housekeepers */
            housekeepers?: unknown[];
            /** @default normal */
            priority: components["schemas"]["TaskPriority"];
        };
        /**
         * PreferencesUpdate
         * @description Partial update of the current user's UI preferences.
         */
        PreferencesUpdate: {
            /** Theme */
            theme?: ("light" | "dark" | "system") | null;
            /** Preferred Language */
            preferred_language?: ("en" | "es") | null;
        };
        /**
         * RequestKind
         * @enum {string}
         */
        RequestKind: "add" | "remove";
        /**
         * RequestResource
         * @description What an access request operates on.
         * @enum {string}
         */
        RequestResource: "staff" | "room";
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "pending" | "approved" | "rejected";
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * RoomAddPayload
         * @description Proposed room for a `room`/`add` request.
         */
        RoomAddPayload: {
            /** Room Number */
            room_number: string;
            /** Floor */
            floor?: number | null;
            /** Room Type */
            room_type?: string | null;
            /** @default clean */
            status: components["schemas"]["RoomStatus"];
        };
        /** RoomCreate */
        RoomCreate: {
            /** Room Number */
            room_number: string;
            /** Floor */
            floor?: number | null;
            /** Room Type */
            room_type?: string | null;
            /** @default clean */
            status: components["schemas"]["RoomStatus"];
        };
        /** RoomRead */
        RoomRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            /** Room Number */
            room_number: string;
            /** Floor */
            floor: number | null;
            /** Room Type */
            room_type: string | null;
            status: components["schemas"]["RoomStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoomStatus
         * @enum {string}
         */
        RoomStatus: "clean" | "dirty" | "in_progress" | "out_of_service";
        /**
         * RoomStatusUpdate
         * @description Status-only update. Managers may change a room's status without the
         *     full-edit (add/rename/delete) rights reserved for platform admins.
         */
        RoomStatusUpdate: {
            status: components["schemas"]["RoomStatus"];
        };
        /** RoomUpdate */
        RoomUpdate: {
            /** Room Number */
            room_number?: string | null;
            /** Floor */
            floor?: number | null;
            /** Room Type */
            room_type?: string | null;
            status?: components["schemas"]["RoomStatus"] | null;
        };
        /**
         * StaffAddPayload
         * @description Proposed staff member for a `staff`/`add` request. No password: a temp
         *     password is generated at approval time and shown once to the admin.
         */
        StaffAddPayload: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /** TaskCreate */
        TaskCreate: {
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /** Assigned To */
            assigned_to?: string | null;
            /** @default pending */
            status: components["schemas"]["TaskStatus"];
            /** @default normal */
            priority: components["schemas"]["TaskPriority"];
            /** Notes */
            notes?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "normal" | "urgent";
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Hotel Id
             * Format: uuid
             */
            hotel_id: string;
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /** Assigned To */
            assigned_to: string | null;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /** Notes */
            notes: string | null;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "pending" | "assigned" | "in_progress" | "completed";
        /** TaskStatusUpdate */
        TaskStatusUpdate: {
            status: components["schemas"]["TaskStatus"];
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Room Id */
            room_id?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            /** Notes */
            notes?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserProvision
         * @description A staff row in a provisioning batch. No password: every provisioned user
         *     gets the batch's shared temporary password and must change it on first login.
         */
        UserProvision: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Hotel Id */
            hotel_id: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /** Must Change Password */
            must_change_password: boolean;
            /**
             * Theme
             * @enum {string}
             */
            theme: "light" | "dark" | "system";
            /**
             * Preferred Language
             * @enum {string}
             */
            preferred_language: "en" | "es";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "manager" | "housekeeper";
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Password */
            password?: string | null;
            /** Name */
            name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_my_preferences_api_v1_auth_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_my_password_api_v1_auth_me_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotels_api_v1_hotels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"][];
                };
            };
        };
    };
    create_hotel_api_v1_hotels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_hotel_api_v1_hotels_provision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelProvisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hotel_api_v1_hotels__hotel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hotel_api_v1_hotels__hotel_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HotelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_hotels__hotel_id__users_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_hotels__hotel_id__users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_hotels__hotel_id__users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_api_v1_hotels__hotel_id__rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_v1_hotels__hotel_id__rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_api_v1_hotels__hotel_id__rooms__room_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_status_api_v1_hotels__hotel_id__rooms__room_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_hotels__hotel_id__tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                assigned_to?: string | null;
            };
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_hotels__hotel_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_dirty_rooms_endpoint_api_v1_hotels__hotel_id__tasks_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirtyRoomImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirtyRoomImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_hotels__hotel_id__tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_hotels__hotel_id__tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_status_api_v1_hotels__hotel_id__tasks__task_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotel_access_requests_api_v1_hotels__hotel_id__access_requests_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"] | null;
            };
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_access_request_api_v1_hotels__hotel_id__access_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_access_requests_api_v1_access_requests_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"] | null;
                hotel_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_access_request_api_v1_access_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestDecision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_access_request_api_v1_access_requests__request_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessRequestReject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_hotels__hotel_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_api_v1_hotels__hotel_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_hotels__hotel_id__api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotel_id: string;
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pms_dirty_rooms_api_v1_integrations_pms_dirty_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PmsDirtyRoomsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirtyRoomImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
